version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresWW
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    build:
      context: ./WizardsWands_sb
      dockerfile: Dockerfile
    container_name: springbootWW
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  angular:
    build:
      context: ./WizardsWands
      dockerfile: Dockerfile
    container_name: angularWW
    ports:
      - "4200:4200"

volumes:
  postgres_data:
